#!/bin/bash

# Author: Ian Flanagan testim.io 2022

myFile="test.txt"
myDelay=5
myURL=$1

# Define Functions 


function updateRepo() {


if [ -e $myFile ]

then
    	echo "The file: " $myFile " does exist."
    	myRandomTxt=$(openssl rand -hex 20)
    	echo "This is a: " $myRandomTxt " test again" > $myFile
		git add .
		git commit -m "Added this string $myRandomTxt to file."
		git push -u origin main
		sleep $myDelay
		open $myURL
else
    	echo "The File:  " $myFile " does not exist."
    	echo "The File: " $myFile " exists "  
		echo "Lets add a file"
		touch myFile
		echo "This is a test" > $myFile
		git add .
		git commit -m "Added file."
		git push -u origin main
		sleep $myDelay
		open $myURL
fi


}



if [ -n "$1" ] ; then 

updateRepo

else
  		echo "Syntax: ./commit <https://github.com/<githubuser>/<githubproject>/actions> "
  		exit 1
	fi
