name: testim-github-actions
on: [push]
jobs:
  run-testimio-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'
      - run: npm install -g @testim/testim-cli 
      - run: testim --version
      - run: testim --test-plan "Demo Plan" --mode "appium" --token "saqYwDP0ZDCL2LitRIHEzGaaHiKmM4LPuE3hVJGgeZ1K4NulwM" --project "bjmdtp2LNM7kcvrO6l2F" --result-label ${{github.run_number}} --config-file myConfigV2.js

